language: "go"

os:
  - linux
  - windows

dist: bionic

jobs:
  include:

    - language: go

      go: "1.13.x"
      env:
        global:
          GO111MODULE=auto

      before_install:
        - echo Starting Building and Testing The Repository

      script:
        - go build -v ./...
        - go test -v ./...
